language: ruby
rvm:
- 2.6.5
cache:
  bundler: true
  directories:
    - .firebase
    - .jekyll-cache
    - vendor/bundle
before_install: gem install bundler
install: bundle install
script: jekyll build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "EU1N5hZtFAUdvIp4EZL0STxU/+GuesR9nDLAeBNwfT55XlR54behDbijCFxEBGcnwK9lK3+TdrDFb7jPwni4+2XK7rhN7Vte2u57F71vQusvEpCpLyaXBsGfvvOkxUwdAM4UfYH6PdOqNYo7p1sSwBeEsL5beKH3QbVCKFRlZYD6uAsETzObA2TZcSV/6Ln2Rd26kQ/zDiXKxfrtIM/MukoDcZx2fPfxwzPvP1MECxuoNpbeGhai4O/iJF/Jp0Mn5PvC5yolIbk0HFqWwqD0pXiV217QMmxERRBObE5xSqlnJuftdisz/XXTayZdLSEzSHm+qkMtfPDdQOAPJcpbaAb49VAERGEPdiUVMng9SIJ/tTAqY3P9uRdxgxZhK3FmC0Tt3lD4bpVFaqJZv/Jq5RlKxnxWw63cUUIg7bUOj7NxVDEL/XrpDjgb6T8giZhdVDVmeQA1vR8by2aazgLMzb5rtkvU83rbyXueG5s8iKGrjgvCBv6dDgkjUOeWvKsirj2rwyce2YJ3wLpOVe3gJIJzIWjRF6ZtK0X3gJjkm14iBiyCh01f1WsWZLKpYXPBmQWQfO+1fITMjRCPLIdzCCJXipmYDQky5ESd4UdXAhEr1pZsaXMBw5sp7/tGlRRHYUr+bvHJ5SVrdzgVlmG5qzwJAamGeoDtNx1f5A5hk8E="
  on:
    branch: master
env:
 - JEKYLL_ENV=production
