language: ruby
rvm:
- 2.6.5
cache:
  bundler: true
  directories:
    - .firebase
    - .jekyll-cache
    - vendor/bundle
before_install: gem install bundler
install: bundle install
script: jekyll build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "SL/HytEY4gFhdSng7aiCu0+qAlh15E9T+WHyUW2bVO1a64WdmzvWt7FvND4WSWWkZHGgggZOhKW4BuNvDYoKr75APG9i8mqGxKNYJ8MQ3vu2B6X9PBwx2yfpf0Tx96xEHRzpF6EqGWtRkViu6zQJTaVKK5p6A+xoT+aDZbOccFpuXINFRi8WM76JRLrn7yKiGCTeA+o9w9RmO/N2a1viyQyklIK/9phHYCmclnAXkJqo8M8UHcx8SczGTCGjDRRws0dE6Orp+44Q+QC/DvmxVFVjAjEHwfr/QO7DN75vkWL7ev0UNW2jBc6Ku52OQDBSimmjEh0oNUttGHh1yc+fcdm08Hk1+x0pyw/SkbMoQt3UKixGo17E9v/ZdFWnigD76AIDovwQuNY0vbhOiM7gh+Mvy9fgxkhRStBsM15WIVsdLNdCUcKNjA38acq6yEunH/vJR2y4OyYTudaeldMyLmPSdJk5gRh0rlo1WeAy0R79gaR05TDg6fC8E8sC9iWAFEPL1lJyMmNzuI65q0Qqy8afDK4FQMp3fHL2GqPuse2gJeVgLbgEmxEUeC0uGhVgTn/n58FfqjC/yYFH3btYkvRxZlx+v+dxiiOHC2Jafcv8SHLJi5gkQarO6IG/4hXeXEk1Nf2pXlsaqdVAc9tC0gs8568L6v7MDzDahD9S5wI="
  on:
    branch: master
env:
 - JEKYLL_ENV=production
